### ISSUE TITLE
azmedservices to be moved to .com or .org domain

### ISSUE THREAD

**Issue by techbelle** [azmedservices/azmedservices.github.io#1]

**Comment by techbelle** [comment]
I see that actually the site is available at arizonamedservices.com too

**Comment by bizarrowill** [comment]
The azmedservices.github.io is not being used anywhere publicly, its only published here so I can send Jake a working version before I take the files here and transfer to bluehost to deploy to the real https://arizonamedservices.com/

**Comment by techbelle** [comment]
https://azmedservices.github.io ? (it's def. available publicly)

**Comment by bizarrowill** [comment]
Gotcha yeah it is live, by publicly I just meant we're not sending it out to anyone directly they would have to seek this address out to know it exists. We're only sending out the actual .com from Bluehost on all marketing material. We can turn this off if we need to or if it would conflict with google results. This repo is not connected to the company site at all it's just my testing environment.
